name: Draft release

on:
  push:
    tags:
      - 'v*'

jobs:
  build-macos:
    name: Build macos/arm64
    runs-on: macos-15
    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - name: Setup go
        uses: actions/setup-go@3041bf56c941b39c61721a86cd11f3bb1338122a # v5
        with:
          go-version-file: "./go.mod"
          cache: false

      - name: Install Wails
        run: ./install-wails.sh

      - name: Build App
        run: wails build -platform darwin/arm64

      - name: Add macOS perms
        run: chmod +x build/bin/*/Contents/MacOS/*

      - name: Codesign
        run: codesign --force -s - build/bin/pickle.app

      - name: Create DMG
        run: |
          cd build/bin
          hdiutil create -volname "Pickle" -srcfolder pickle.app -ov -format UDZO pickle-macos-arm64.dmg
          rm -rf pickle.app

      - uses: actions/upload-artifact@v4
        with:
          name: macos-arm64
          path: |
            */bin/*

  build-windows:
    name: Build windows/amd64
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - name: Setup go
        uses: actions/setup-go@3041bf56c941b39c61721a86cd11f3bb1338122a # v5
        with:
          go-version-file: "./go.mod"
          cache: false

      - name: Install Wails
        run: ./install-wails.ps1

      - name: Build App
        run: wails build -platform windows/amd64 -webview2 embed

      - uses: actions/upload-artifact@v4
        with:
          name: windows-amd64
          path: |
            *\bin\*

  draft-release:
    name: Draft release
    runs-on: ubuntu-latest
    needs: [build-macos,build-windows]
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Get tag
        id: get_tag
        run: echo "tag=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

      - name: Download macos/arm64
        uses: actions/download-artifact@v4
        with:
          name: macos-arm64
          path: .
      - name: Download windows/amd64
        uses: actions/download-artifact@v4
        with:
          name: windows-amd64
          path: .

      - name: Compress pickle
        run: |
          ls -lahR ./build
          cd ./build/bin
          zip -r pickle-windows-amd64.zip pickle.exe && rm -rf pickle.exe

      - name: Create release
        run: gh release create -d --generate-notes ${{ steps.get_tag.outputs.tag }} ./build/bin/*
        env:
           GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

