name: Pull request

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  lint:
    name: Lint Go
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - name: Setup go
        uses: actions/setup-go@3041bf56c941b39c61721a86cd11f3bb1338122a # v5
        with:
          go-version-file: "./go.mod"
          cache: false
      - name: Install
        run: |
          go install github.com/gordonklaus/ineffassign@latest
          go install honnef.co/go/tools/cmd/staticcheck@latest
          go install github.com/kisielk/errcheck@latest
          go install github.com/google/go-licenses@latest
          mkdir frontend/dist
          touch frontend/dist/placeholder
      - name: format
        if: always()
        run: test -z $(gofmt -l ./.. | grep -v vendor)
      - name: vet
        if: always()
        run: go vet ./...
      - name: errcheck
        if: always()
        run: errcheck ./...
      - name: ineffassign
        if: always()
        run: ineffassign ./...
      - name: staticcheck
        if: always()
        run: staticcheck ./...
      - name: license
        if: always()
        run: go-licenses check --ignore github.com/bradenrayhorn/pickle --confidence_threshold 0.85 ./...

  build:
    name: Verify build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - name: Setup go
        uses: actions/setup-go@3041bf56c941b39c61721a86cd11f3bb1338122a # v5
        with:
          go-version-file: "./go.mod"
          cache: false

      - name: Install Wails
        run: ./install-wails.sh

      - name: Build
        run: wails build -tags webkit2_41

  lint-svelte:
    name: Lint Svelte
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - name: Setup go
        uses: actions/setup-go@3041bf56c941b39c61721a86cd11f3bb1338122a # v5
        with:
          go-version-file: "./go.mod"
          cache: false

      - name: Setup node
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
        with:
          node-version-file: "./frontend/.nvmrc"

      - name: Install Wails
        run: ./install-wails.sh

      - name: Build Wails
        run: wails build

      - name: Prettier and ESLint
        run: npm run lint
        working-directory: ./frontend
        if: always()

      - name: svelte-check
        run: npm run check
        working-directory: ./frontend
        if: always()

  test-e2e:
    name: Test E2E
    runs-on: macos-15
    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Setup node
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
        with:
          node-version-file: "./frontend/.nvmrc"

      - name: Setup go
        uses: actions/setup-go@3041bf56c941b39c61721a86cd11f3bb1338122a # v5
        with:
          go-version-file: "./go.mod"
          cache: false

      - name: Install Wails
        run: ./install-wails.sh

      - name: Build Wails
        run: wails build

      - name: Install Playwright dependencies
        working-directory: ./e2e
        run: npm install

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
        working-directory: ./e2e

      - name: Run Playwright tests
        working-directory: ./e2e
        run: npm run test

      - uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: e2e/playwright-report/
          retention-days: 2
